language: php

dist: trusty
sudo: required

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.0
      env: SYMFONY_VERSION='2.7.*'
    - php: 7.0
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.0
      env: SYMFONY_VERSION='^3.0'
  fast_finish: true

before_install:
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc

before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.0.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.0.0.deb
  - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install -b mapper-attachments
  - sudo service elasticsearch restart
  - sh -c 'echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs
  - composer update --prefer-dist --no-progress --no-suggest --ignore-platform-reqs $COMPOSER_FLAGS
  - composer update --prefer-dist --no-progress --no-suggest $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

services:
  - elasticsearch

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
